# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in blogger_reader.gemspec
gemspec

gem "activesupport"

gem "irb"
gem "rake", "~> 13.0"
gem "minitest", "~> 5.16"

gem "standard", "~> 1.50.0"
